services:
    mariadb:
        image: mariadb:12-ubi
        container_name: mariadb
        restart: always
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: ""
        ports:
            - "8080:80"

volumes:
    mariadb_data:
